# Site settings
name: dosic
title: dosic
description: Jekyll Theme Minimal Resume
baseurl: /
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: dosic
user_description: open source test
user_title: Software Engineer
email: mauriurraco@gmail.com
# twitter_username: lorem_ipsum
instagram_username: mauriciourraco7
facebook_username: mauricio.urraco
linkedin_username: murraco
github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

